
services:
  cccd_backend:
    build: 
      context: ./docker_backend
      dockerfile: Dockerfile
    container_name: cccd_ai_service
    ports:
      - "8000:8000"
    volumes:
      - ./paddle_models:/root/.paddleocr  # Lưu model OCR để lần sau khởi động không phải tải lại